services:
  synapse:
    container_name: synapse
    image: ghcr.io/element-hq/synapse:latest
    # Since synapse does not retry to connect to the database, restart upon
    # failure
    restart: unless-stopped
    # See the readme for a full documentation of the environment settings
    environment:
    # config file location - be sure to create one first!
    # https://github.com/matrix-org/synapse/tree/develop/docker#generating-a-configuration-file
      - SYNAPSE_CONFIG_PATH=/data/homeserver.yaml
      - UID=${PUID}
      - GID=${GUID}
    volumes:
      - ${STORAGE}:/data #location of config
      - ${STORAGE}/media_store:/data/media_store #larger drive for storage
      - ${STORAGE}/uploads:/data/uploads #larger drive for storage
    depends_on:
    # We're going to use an external database as it's more performant for multiple
    # users
      - synapse-db
    networks:
        synapse:
        traefik-public:
    # Uncomment if not using a proxy. In order to expose Synapse, remove one of the following, 
    # you might for instance expose the TLS port directly:
    #ports:
    # - 8448:8448/tcp
    # - 8008:8008/tcp

    # ... or use a reverse proxy, here is an example for traefik:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.synapse.entrypoints=http"
      - "traefik.http.routers.synapse.rule=Host(`matrix.local.serbicki.com`)"
      - "traefik.http.middlewares.synapse-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.synapse.middlewares=synapse-https-redirect"
      - "traefik.http.routers.synapse-secure.entrypoints=https"
      - "traefik.http.routers.synapse-secure.rule=Host(`matrix.local.serbicki.com`)"
      - "traefik.http.routers.synapse-secure.tls=true"
      - "traefik.http.routers.synapse-secure.service=synapse"
      - "traefik.http.services.synapse.loadbalancer.server.port=8008"
      - "traefik.docker.network=traefik-public"
        
  synapse-db:
    image: docker.io/postgres:15-alpine
    container_name: synapse-db
    restart: unless-stopped
    # Change password below, of course!
    environment:
      - POSTGRES_USER=synapse_user
      - POSTGRES_PASSWORD=postgres_password
      - POSTGRES_DB=synapse
      # ensure the database gets created correctly
      # https://github.com/matrix-org/synapse/blob/master/docs/postgres.md#set-up-database
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8 --lc-collate=C --lc-ctype=C
    volumes:
      # You may store the database tables in a local folder..
      - /home/ubuntu/docker/synapse-db/schemas:/var/lib/postgresql/data
      # .. or store them on some high performance storage for better results
      # - /path/to/ssd/storage:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT}:5432
    networks:
       synapse:
    secrets:
      - postgres_password

networks:
  synapse:
  traefik-public:
    external: true

secrets:
  postgres_password:
    file: ${CONFIGS}/postgres_pass.txt
